# Generated by Django 4.2 on 2023-06-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_image',
            field=models.ImageField(default='', upload_to='categories'),
        ),
    ]
